### PR TITLE
Internationalize copy to something more valley-esque

### PR DESCRIPTION
**Pull request by snaily**
@subho007 To give you guys an idea of what we mean when the website copy doesn't sound perfectly international, we sat down and exaggerated in the opposite direction:
- More direct and slightly more casual language
- Avoid some constructions particularly common in Indian English (loopholes, 360 degrees...)
- Get a little quirky and themed (zen, calm, sensei...)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/appknox/appknox.github.io/pull/6" target="_blank">ReviewNinja

**Comment by subho007** [comment]
agreed @snaily with the pointers.

There's a merge conflict here. Will you take it up, or should I proceed forward and resolve it?

**Comment by snaily** [comment]
I don't think you want to merge this straight off - the intention was for this to be a basis for discussion, not a solution.

**Comment by subho007** [comment]
oh got it @snaily 👍

**Comment by subho007** [comment]
@snaily We got your feedbacks, we will be incorporating those directly. For now, I am closing this PR

**Pull request closed without merging**
