### PR TITLE
Adding testimonial

### PR DESCRIPTION
**Pull request by yashwin**

### CODE REVIEW

**Comment by subho007** [comment]
@yashwin did you check before pushing the PR ?
screen shot 2016-07-09 at 8 48 23 pm
Last time while integrating the pictures the same thing happened, which I fixed previously

**Comment by yashwin** [comment]
Yeah. I did check this. @subho007

**Comment by subho007** [comment]
@yashwin look at the pic.  Please fix it

**Comment by yashwin** [comment]
@subho007 : Fixed. I guess there were some cookie issues.

**Pull request merged**
