### PR TITLE
[Refactor] Create Custom tags

### PR DESCRIPTION
**Pull request by dhilipsiva**
@subho007 @jitk14 Don't merge his yet.

### CODE REVIEW

**Comment by subho007** [comment]
@dhilipsiva any updates on this PR ?

**Comment by dhilipsiva** [comment]
@subho007 I have done everything. But A small configuration proble and tags are not working. Not able to find out what. Will look into it. Meanwhile you can have a look. As usual - I should have stuck in a silly problem. But refactor part is done 😛

**Comment by subho007** [comment]
@dhilipsiva ok 😂

**Comment by subho007** [comment]
@dhilipsiva closing this off for now. We will think of a new plug-n-play later on

**Comment by dhilipsiva** [comment]
@subho007 Okies. But dont delete the branch. Will work on this next weekend.

**Comment by subho007** [comment]
okies @dhilipsiva 👍

**Pull request closed without merging**
